name: cron-mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天早上0点

jobs:
  mirror:
    name: Mirror on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: alexv587/charging-oss
          ref: gh-pages
      - name: Run Script
        run: |
          git remote remove origin
          git remote add origin https://github.com/${{github.repository}}.git
          git push
        
        
